### ISSUE TITLE
Port Melodic Gribot to ROS2

### ISSUE THREAD

**Issue by andrestoga** [guycorbaz/gribot#35]
Hi,

What if we focus in developing Gribot in ROS2 which eventually is going to be the ROS stantard. I can start porting the existing Melodic workspace to ROS2 workspace by creating a branch.

Best,

**Comment by guycorbaz** [comment]
Hello,
Yes, it is a good idea. However, I don't know what are the effort to do it and if all modules presently used by Gribot are already ported on ROS2.
If you need modification of your access right, don't hesitate to tell me.
egards, Guy.

**Comment by andrestoga** [comment]
Yeah, that's a problem. What we can do is to work in both versions(ROS and ROS2) in parallel in separate branches.

**Comment by guycorbaz** [comment]
I see two possibilities:
- creating a branch for ROS
- creating a branch for ROS 2
So we could work on the two versions in parallel, knowing they are probably not compatible.

My only issue is only concerning modules. I have no issue to do a "big bang" in migrating to ROS2.

**Comment by andrestoga** [comment]
Agree. Not all modules will be in ROS2. Plus there will be another version for ROS1 in May 23rd. Probably is just better to focus right now on ROS1 Melodic. Then, check if the new version of ROS1, ROS Noetic, is compatible with ROS Melodic and move to that version. ROS2 will be a future feature.
